package com.sartorius.tma.enumeration;


public enum EmailContext {
  WELCOME_USER,
  RESET_PWD,
  ADMIN_VALIDATE_ANNOUNCEMENT,
  NOTIF_EXPERT_ACCEPT_OFFER,
  NOTIF_EXPERT_DECLINE_OFFER,
  NOTIF_EXPERT_DECLINE_OFFER_AFTER_ACCEPT,
  NOTIF_EXPERT_PUB_ANNOUNCEMENT,
  NOTIF_USER_PUB_ANNOUNCEMENT,
  NOTIF_USER_NEW_OFFER,
  NOTIF_USER_OFFER_NOT_VALID,
  NOTIF_USER_OFFER_VALID,
  NOTIF_EXPERT_VALIDATION_ACCEPTED,
  NOTIF_EXPERT_VALIDATION_REFUSED,
  NOTIF_ADMIN_VALIDATE_ACCOUNT_REQUEST,
  NOTIF_USER_ANNOUNCEMENT_REFUSED,
  NOTIF_ADMIN_NEW_CONTACT_MESSAGE,
  NOTIF_EXPERT_PAYMENT_VALID,
  NOTIF_EXPERT_MESSAGE_ADMIN,
  NOTIF_USER_PAYMENT_VALID,
  NOTIF_EXPERT_ACTIVE_BUT_NOT_VALIDATED_MESSAGE,
  NOTIF_EXPERT_ACTIVE_AND_VALIDATED_MESSAGE,
  NOTIF_EXPERT_NOT_ACTIVE_BUT_NOT_DEACTIVATED_MESSAGE,
  NOTIF_USER_START_MEET,
  NOTIF_EXPERT_PRESTATION_VALID,
  NOTIF_EXPERT_PRESTATION_NOT_VALID,
  NOTIF_EXPERT_PAYMENT_FEES_VALID,
  NOTIF_EXPERT_PAYMENT_FEES_NOT_VALID,
  NOTIF_EXPERT_ASSIGNMENT_TO_COURSE,
  NOTIF_USER_ASSIGNMENT_TO_COURSE

}
