rootLogger.level=INFO
property.filename=edu365-back
property.filepath=/var/log/edu365
property.filesize=10 MB
appenders=R, console
appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%style{%d{ISO8601}}{black} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%C{1.}}{bright,yellow}: %msg%n%throwable
appender.R.type=RollingFile
appender.R.name=RollingFile
appender.R.fileName=${filepath}/${filename}.log
appender.R.filePattern=${filepath}/archive/${filename}-%d{dd-MM-yyyy}-%i.log.gz
appender.R.layout.type=PatternLayout
appender.R.layout.pattern=%d %p %C{1.} [%t] %m%n
appender.R.policies.type=Policies
appender.R.policies.time.type=TimeBasedTriggeringPolicy
appender.R.policies.time.interval=1
appender.R.policies.size.type=SizeBasedTriggeringPolicy
appender.R.policies.size.size=${filesize}
appender.R.policies.startup.type=OnStartupTriggeringPolicy
rootLogger.appenderRefs=R, console
rootLogger.appenderRef.console.ref=STDOUT
rootLogger.appenderRef.R.ref=RollingFile